apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cli-tools.fullname" . }}
  labels:
    {{- include "cli-tools.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cli-tools.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cli-tools.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /resources
              name: sdd-resources
            - mountPath: /common-resources
              name: sdd-common-resources
      volumes:
        - name: sdd-resources
          hostPath:
            path: {{ .Values.volumes.resource.hostPath }}
        - name: sdd-common-resources
          hostPath:
            path: {{ .Values.volumes.commonResource.hostPath }}
