apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azurite.fullname" . }}
  labels:
    {{- include "azurite.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "azurite.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "azurite.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "azurite.fullname" . }}-configmap
