apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "newman.fullname" . }}-configmap
  labels:
    {{- include "newman.labels" . | nindent 4 }}
data:
  API_KEY: ApiKeyDefaultValue
  EDC_HOST: company1:company2:company3
  ASSETS_STORAGE_ACCOUNT: company1assets:company2assets:company3assets
  PARTICIPANT_ID: company1:company2:company3