{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "newman.fullname" . }}
  labels:
    {{- include "newman.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "newman.selectorLabels" . | nindent 4 }}
{{- end }}