apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "did-server.fullname" . }}
  labels:
    {{- include "did-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "did-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "did-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: sdd
      volumes:
        - name: sdd
          hostPath:
            path: {{ .Values.volumes.hostPath }}
